### ISSUE TITLE
Code used in the Case Study with the C-sanitise privacy model

### ISSUE THREAD

**Issue by mariasierro** [IldikoPilan/anonymisation_ACL2021#1]
Hello!

My name is María and I am a Master's student of Language Analysis and Processing at the University of the Basque Country (UPV/EHU) in Spain.

I am currently working on my Master's thesis and I am focusing on the anonymization of texts in Spanish and French.

I found your work very interesting and inspiring :)

I saw that you already uploaded the datasets that you used in your work, but I was wondering if it would be possible for you to please upload the code that you used for examining the performance of C-sanitise. It would be really useful because it would allow me replicate your experiments and I could try to apply it to my own datasets in Spanish and French.

Thank you!

Regards,

María Sierro

**Comment by plison** [comment]
For the C-sanitize approach, you should perhaps contact our colleagues David Sánchez and Montserrat Batet from the Universitat Rovira i Virgili, they were the one doing that work. But from I remember, it wasn't possible to fully automate the process due to access restrictions with the web search (Google will block you quickly if you try to use their search engine programmatically), so the process was partly manual. Which is one of the reason for the small corpus size employed for the case study.
